/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Oct 14 10:33:35 2019. */

#include "Nazhi.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeviceId_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceId, dev, dev, 0),
    PB_LAST_FIELD
};

const pb_field_t SendDataBack_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, SendDataBack, Id, Id, &DeviceId_fields),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, SendDataBack, SeriNum, Id, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, SendDataBack, Error, SeriNum, 0),
    PB_LAST_FIELD
};

const pb_field_t PhotoInfo_fields[13] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, PhotoInfo, Id, Id, &DeviceId_fields),
    PB_FIELD(  2, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, protocol_ver, Id, 0),
    PB_FIELD(  3, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, firmware_ver, protocol_ver, 0),
    PB_FIELD(  4, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, code_ver, firmware_ver, 0),
    PB_FIELD(  5, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, build_time, code_ver, 0),
    PB_FIELD(  6, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, kernel_version, build_time, 0),
    PB_FIELD(  7, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, lcd_type, kernel_version, 0),
    PB_FIELD(  8, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, systemp_type, lcd_type, 0),
    PB_FIELD(  9, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, plateform, systemp_type, 0),
    PB_FIELD( 10, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, sensor_type, plateform, 0),
    PB_FIELD( 11, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, algorithm_ver, sensor_type, 0),
    PB_FIELD( 12, STRING  , REQUIRED, CALLBACK, OTHER, PhotoInfo, min_sdk_ver, algorithm_ver, 0),
    PB_LAST_FIELD
};

const pb_field_t FaceFlags_fields[12] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, FaceFlags, faceID, faceID, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, FaceFlags, faceName, faceID, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, role, faceName, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, wgCardNO, role, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, effectTime, wgCardNO, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, effectStartTime, effectTime, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, version, effectStartTime, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, wgCardNOLong, version, 0),
    PB_FIELD(  9, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, ScheduleMode, wgCardNOLong, 0),
    PB_FIELD( 10, INT32   , REQUIRED, STATIC  , OTHER, FaceFlags, resv2, ScheduleMode, 0),
    PB_FIELD( 11, STRING  , REQUIRED, STATIC  , OTHER, FaceFlags, userParam, resv2, 0),
    PB_LAST_FIELD
};

const pb_field_t Picture_fields[6] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Picture, jpgName, jpgName, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Picture, jpgLengt, jpgName, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Picture, picId, jpgLengt, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, Picture, libId, picId, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, Picture, libName, libId, 0),
    PB_LAST_FIELD
};

const pb_field_t AddFcae_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, AddFcae, face, face, &FaceFlags_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, AddFcae, picture, face, &Picture_fields),
    PB_LAST_FIELD
};

const pb_field_t FaceRecord_fields[10] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, FaceRecord, face, face, &FaceFlags_fields),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, FaceRecord, picture, face, &Picture_fields),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, FaceRecord, dev, picture, &DeviceId_fields),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, FaceRecord, tvSec, dev, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, FaceRecord, tvUsec, tvSec, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, FaceRecord, matched, tvUsec, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, FaceRecord, sourceOfReg, matched, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, FaceRecord, living, sourceOfReg, 0),
    PB_FIELD(  9, INT32   , REQUIRED, STATIC  , OTHER, FaceRecord, hatColour, living, 0),
    PB_LAST_FIELD
};

const pb_field_t OperationFaceId_fields[4] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, OperationFaceId, dev, dev, &DeviceId_fields),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, OperationFaceId, faceId, dev, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, OperationFaceId, operation, faceId, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SendDataBack, Id) < 65536 && pb_membersize(PhotoInfo, Id) < 65536 && pb_membersize(AddFcae, face) < 65536 && pb_membersize(AddFcae, picture) < 65536 && pb_membersize(FaceRecord, face) < 65536 && pb_membersize(FaceRecord, picture) < 65536 && pb_membersize(FaceRecord, dev) < 65536 && pb_membersize(OperationFaceId, dev) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_DeviceId_SendDataBack_PhotoInfo_FaceFlags_Picture_AddFcae_FaceRecord_OperationFaceId)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SendDataBack, Id) < 256 && pb_membersize(PhotoInfo, Id) < 256 && pb_membersize(AddFcae, face) < 256 && pb_membersize(AddFcae, picture) < 256 && pb_membersize(FaceRecord, face) < 256 && pb_membersize(FaceRecord, picture) < 256 && pb_membersize(FaceRecord, dev) < 256 && pb_membersize(OperationFaceId, dev) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_DeviceId_SendDataBack_PhotoInfo_FaceFlags_Picture_AddFcae_FaceRecord_OperationFaceId)
#endif


/* @@protoc_insertion_point(eof) */
